### PR TITLE
Fixing bug where client list errantly shows empty state. Resolves #119.

### LINKED ISSUE #119: Target saying "no search results" shows up on initial load for Client List

### PR DESCRIPTION
**Pull request by joeldenning**
See #119

### CODE REVIEW

File: frontend/client-list/client-list.component.tsx [hunk 1]
```diff
@@ -18,9 +18,7 @@ export default function ClientList(props: ClientListProps) {
   useClientsApi(apiState, dispatchApiState);
   useFrontendUrlParams(apiState, dispatchApiState);
 
-  const fetchingClient =
-    apiState.status === ApiStateStatus.fetching ||
-    apiState.status === ApiStateStatus.shouldFetch;
+  const fetchingClient = apiState.status !== ApiStateStatus.fetched;
```
Comment (joeldenning) [inline frontend/client-list/client-list.component.tsx]: The bug was caused by `fetchingClient` starting out as `false` because the initial state was starting with the apiState.status being `fetched`.
